### ISSUE TITLE
Using Shaders

### ISSUE THREAD

**Issue by DCubix** [jtsiomb/libdrawtext#1]
I can't figure out how to use shaders with this library. I would like to have an example...

**Comment by jtsiomb** [comment]
On Mon, Mar 16, 2015 at 08:49:06AM -0700, Diego Lopes wrote:
> I can't figure out how to use shaders with this library. I would like
> to have an example...

You don't have to do anything special to use shaders. libdrawtext
doesn't unset or override your active shader program. Do you have a
specific problem?

-- 
John Tsiombikas
http://nuclear.mutantstargoat.com/

**Comment by DCubix** [comment]
Oh, nvm, I was binding the shader after dtx_string.
