### ISSUE TITLE
Ubuntu cannot find libdrawtext.so.0

### ISSUE THREAD

**Issue by FilipeChagasDev** [jtsiomb/libdrawtext#10]
Even after make install, ubuntu can not find the libdrawtext.so.0 file. I was able to fix this with the command: _sudo cp libdrawtext/ libdrawtext.so.0 /usr/lib_

**Comment by jtsiomb** [comment]
This is not a libdrawtext bug. It's not a bug at all. The default prefix is /usr/local as it should. If ubuntu doesn't have /usr/local/lib in its search paths then you need to add it. Alternatively you can install libdrawtext in /usr if you prefer. Just run `./configure --prefix=/usr` before running `make install`.

I'm closing this bug report. If I misunderstood and that's not what you meant, please re-open.
