### ISSUE TITLE
Build fails on macOS with Xcode 15

### ISSUE THREAD

**Issue by fxcoudert** [jtsiomb/libdrawtext#19]
Build fails on recent macOS (with Xcode 15):

```
  src/drawgl.c:215:3: error: call to undeclared function 'gluBuild2DMipmaps'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
                  gluBuild2DMipmaps(GL_TEXTURE_2D, GL_ALPHA, gmap->xsz, gmap->ysz, GL_ALPHA, GL_UNSIGNED_BYTE, gmap->pixels);
                  ^
  1 error generated.
  make: *** [src/drawgl.o] Error 1
```

I think it is missing the right header?

**Comment by jtsiomb** [comment]
Try adding `#include <OpenGL/glu.h>` right after `#include <OpenGL/gl.h>`. Does it solve the problem?

**Comment by jtsiomb** [comment]
Nevermind, I've set up an automated build for macosx to see for myself, and fixed this along with a couple of other issues like the example programs not compiling on macos. Feel free to reopen if you continue to have problems with this.
